server:
  port: 9201

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          # 开启从注册中心动态创建路由的功能
          enabled: true
          # 使用小写服务名（默认是大写）
          lower-case-service-id: true
      routes:
        - id: prefixpath_route
          # 此处需要lb协议
          uri: lb://user-service
          predicates:
            - Method=GET
          filters:
            - PrefixPath=/user

# 注册中心设置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/