# 指定运行端口
server:
  port: 8002

# 指定服务名称
spring:
  application:
    name: eureka-client

eureka:
  client:
    # 注册到Eureka的注册中心
    register-with-eureka: true
    # 获取注册实例列表
    fetch-registry: true
    service-url:
      # 同时注册到两个中心
      defaultZone: http://peer1:8082/eureka/,http://peer2:8083/eureka/
