# 服务端口
server:
  port: 8601

# 应用名称
spring:
  application:
    name: turbine-service

eureka:
  client:
    # 将服务注册到注册中心
    register-with-eureka: true
    # 获取注册中心服务
    fetch-registry: true
    service-url:
      # 配置注册中心地址
      defaultZone: http://localhost:8081/eureka

turbine:
  # 指定需要收集信息的服务名称
  app-config: hystrix-service
  # 指定服务所属集群
  cluster-name-expression: new String('default')
  # 以主机名和端口号区分服务
  combine-host-port: true
