server:
  port: 8013

spring:
  application:
    name: eureka-security-server
  security:
    user:
      # 配置spring security登录用户名和密码
      name: admin
      password: 123456

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
