# 指定运行端口
server:
  port: 8081

# 指定服务名称
spring:
  application:
    name: eureka-server

# 指定主机地址
eureka:
  instance:
    hostname: localhost
  client:
    # 指定是否从注册中心获取服务
    fetch-registry: false
    # 指定是否将服务注册到注册中心
    register-with-eureka: false
