# 服务端口
server:
  port: 8301

# 服务名称
spring:
  application:
    name: ribbon-service

eureka:
  client:
    # 指定在eureka注册中心中注册服务
    register-with-eureka: true
    # 获取Eureka注册中心的注册列表等服务
    fetch-registry: true
    service-url:
      # 默认注册地址
      defaultZone: http://localhost:8081/eureka/

# 设置接口调用地址
service-url:
  user-service: http://user-service



